[build]
builder = "docker"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet 통합디비.dll"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
maxRestartCount = 3
